msg: Polymath 3
project: pm3
filename: Polymath3
urls: ['http://gowers.wordpress.com/2009/01/27/is-massively-collaborative-mathematics-possible/',
 'http://gowers.wordpress.com/2009/02/01/a-combinatorial-approach-to-density-hales-jewett/',
 'http://terrytao.wordpress.com/2009/02/05/upper-and-lower-bounds-for-the-density-hales-jewett-problem/',
 'http://gowers.wordpress.com/2009/02/06/dhj-the-triangle-removal-approach/',
 'http://gowers.wordpress.com/2009/02/08/dhj-quasirandomness-and-obstructions-to-uniformity/',
 'http://gowers.wordpress.com/2009/02/13/dhj-possible-proof-strategies/',
 'http://terrytao.wordpress.com/2009/02/11/a-reading-seminar-on-density-hales-jewett/',
 'http://terrytao.wordpress.com/2009/02/13/bounds-for-the-first-few-density-hales-jewett-numbers-and-related-quantities/',
 'http://gowers.wordpress.com/2009/02/23/brief-review-of-polymath1/',
 'http://gowers.wordpress.com/2009/03/02/dhj3-851-899/',
 'http://terrytao.wordpress.com/2009/03/04/dhj3-900-999-density-hales-jewett-type-numbers/',
 'http://gowers.wordpress.com/2009/03/10/problem-solved-probably/',
 'http://gowers.wordpress.com/2009/03/10/polymath1-and-open-collaborative-mathematics/',
 'http://gowers.wordpress.com/2009/03/16/dhj3-and-related-results-1050-1099/',
 'http://terrytao.wordpress.com/2009/03/14/dhj3-1100-1199-density-hales-jewett-type-numbers/',
 'http://gilkalai.wordpress.com/2009/03/25/an-open-discussion-and-polls-around-roths-theorem/',
 'http://terrytao.wordpress.com/2009/03/30/dhjk-1200-1299-density-hales-jewett-type-numberpyts/',
 'http://terrytao.wordpress.com/2009/05/22/dhj-writing-the-second-paper/',
 'http://terrytao.wordpress.com/2009/06/14/dhj-still-writing-the-second-paper/',
 'http://gowers.wordpress.com/2009/06/25/dhj-write-up-and-other-matters/',
 'http://terrytao.wordpress.com/2009/07/09/dhj-writing-the-second-paper-iii/',
 'http://terrytao.wordpress.com/2010/01/15/density-hales-jewett-and-moser-numbers-nearing-the-final-draft/']
implicit_refs: ["a-combinatorial-approach-to-density-hales-jewett",
  "upper-and-lower-bounds-for-the-density-hales-jewett-problem",
  "dhj-the-triangle-removal-approach",
  "dhj-quasirandomness-and-obstructions-to-uniformity",
  "dhj-possible-proof-strategies",
  "a-reading-seminar-on-density-hales-jewett",
  "bounds-for-the-first-few-density-hales-jewett-numbers-and-related-quantities",
  "brief-review-of-polymath1",
  "dhj3-851-899",
  "dhj3-900-999-density-hales-jewett-type-numbers",
  "problem-solved-probably",
  "dhj3-and-related-results-1050-1099",
  "dhj3-1100-1199-density-hales-jewett-type-numbers",
  "dhj3-1100-1199-density-hales-jewett-type-numbers",
  "dhjk-1200-1299-density-hales-jewett-type-numbers"]
type: Gowers
parser: html.parser
cmap: Paired
show_labels_comments: False
show_labels_authors: True
vmin: 0
vmax: 100
style: seaborn-talk
first_date: 2000-01-01 00:00:00
last_date: 2016-12-31 00:00:00
