msg: Testing with full Polymath 1
filename: Polymath1
urls: ["http://gowers.wordpress.com/2009/02/01/a-combinatorial-approach-to-density-hales-jewett/",
"http://terrytao.wordpress.com/2009/02/05/upper-and-lower-bounds-for-the-density-hales-jewett-problem/",
"http://gowers.wordpress.com/2009/02/06/dhj-the-triangle-removal-approach/",
"http://gowers.wordpress.com/2009/02/08/dhj-quasirandomness-and-obstructions-to-uniformity",
"http://gowers.wordpress.com/2009/02/13/dhj-possible-proof-strategies/#more-441/",
"http://terrytao.wordpress.com/2009/02/11/a-reading-seminar-on-density-hales-jewett/",
"http://terrytao.wordpress.com/2009/02/13/bounds-for-the-first-few-density-hales-jewett-numbers-and-related-quantities/",
"http://gowers.wordpress.com/2009/02/23/brief-review-of-polymath1/",
"http://gowers.wordpress.com/2009/03/02/dhj3-851-899/",
"http://terrytao.wordpress.com/2009/03/04/dhj3-900-999-density-hales-jewett-type-numbers/",
"http://gowers.wordpress.com/2009/03/10/problem-solved-probably/",
"http://gowers.wordpress.com/2009/03/16/dhj3-and-related-results-1050-1099/",
"http://terrytao.wordpress.com/2009/03/14/dhj3-1100-1199-density-hales-jewett-type-numbers/",
"http://terrytao.wordpress.com/2009/03/30/dhjk-1200-1299-density-hales-jewett-type-numbers/"]
type: Gowers
parser: html.parser
cmap: Paired
show_labels_comments: False
show_labels_authors: True
vmin: 0
vmax: 100
