msg: Polymath 8
filename: Polymath8
urls: ["https://sbseminar.wordpress.com/2013/05/30/i-just-cant-resist-there-are-infinitely-many-pairs-of-primes-at-most-59470640-apart/"]
type: Gowers
parser: html.parser
cmap: Paired
show_labels_comments: False
show_labels_authors: True
vmin: 0
vmax: 100
